import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type Lang = "de" | "en";

const STORAGE_KEY = "@swipet_language";

// ─── Translations ────────────────────────────────────────────────────────────

export const translations = {
  de: {
    // ── Splash / Index ──
    splash_dog_seeker_title: "Hundesuchende",
    splash_dog_seeker_sub: "Finde deinen perfekten Hund",
    splash_dog_owner_title: "Hundehaber",
    splash_dog_owner_sub: "Gassidate & Zucht für Hundebesitzer",
    splash_shelter_title: "Tierheim",
    splash_shelter_sub: "Tiere verwalten & Anfragen bearbeiten",
    splash_login_link: "Bereits registriert? Anmelden →",

    // ── Auth ──
    login_welcome_back: "Willkommen zurück!",
    login_title: "Anmelden",
    login_email: "E-Mail",
    login_email_placeholder: "deine@email.de",
    login_password: "Passwort",
    login_btn: "Anmelden",
    login_or: "oder",
    login_google: "Mit Google anmelden",
    login_apple: "Mit Apple anmelden",
    login_no_account: "Noch kein Konto?",
    login_register: "Registrieren",
    login_err_missing: "Fehlende Angaben",
    login_err_missing_msg: "Bitte E-Mail und Passwort eingeben.",
    login_err_failed: "Login fehlgeschlagen",

    // ── Register ──
    register_back: "← Zurück",
    register_step_role_title: "Wer bist du?",
    register_step_role_sub: "Wähle deine Rolle um loszulegen",
    register_step_details_title: "Dein Konto",
    register_step_details_sub: "Erstelle dein kostenloses Konto",
    register_role_adoptant_label: "Ich suche ein Tier",
    register_role_adoptant_desc: "Adoptiere ein Tier aus dem Tierheim",
    register_role_tierhalter_label: "Ich habe ein Tier",
    register_role_tierhalter_desc: "Finde Gassi- & Spieldatepartner",
    register_role_tierheim_label: "Ich bin ein Tierheim",
    register_role_tierheim_desc: "Vermittle Tiere an liebevolle Familien",
    register_next: "Weiter →",
    register_name: "Name",
    register_name_placeholder: "Dein Name",
    register_email_placeholder: "deine@email.de",
    register_password_placeholder: "Mindestens 6 Zeichen",
    register_change: "ändern",
    register_create_btn: "Konto erstellen 🎉",
    register_has_account: "Bereits ein Konto?",
    register_sign_in: "Anmelden",
    register_err_missing: "Fehlende Angaben",
    register_err_missing_msg: "Bitte alle Felder ausfüllen.",
    register_err_pw_short: "Passwort zu kurz",
    register_err_pw_short_msg: "Mindestens 6 Zeichen erforderlich.",
    register_err_no_user: "Kein Benutzer erstellt.",
    register_err_failed: "Registrierung fehlgeschlagen",
    register_pick_role: "Rolle wählen",
    register_pick_role_msg: "Bitte wähle eine Rolle um fortzufahren.",

    // ── Onboarding Adoptant ──
    onb_step: "Schritt",
    onb_of: "von",
    onb_housing_title: "Wie wohnst du?",
    onb_housing_sub: "Das hilft uns, passende Tiere zu finden.",
    onb_housing_apartment: "🏢 Wohnung",
    onb_housing_house: "🏡 Haus",
    onb_housing_garden: "🌿 Haus mit Garten",
    onb_housing_farm: "🚜 Bauernhof",
    onb_exp_title: "Deine Erfahrung mit Tieren?",
    onb_exp_sub: "Ehrlich bleiben — für dein und das Wohl des Tieres.",
    onb_exp_beginner: "🌱 Anfänger",
    onb_exp_beginner_sub: "Erstes Tier",
    onb_exp_intermediate: "⭐ Fortgeschritten",
    onb_exp_intermediate_sub: "Schon Erfahrung",
    onb_exp_pro: "🏆 Profi",
    onb_exp_pro_sub: "Viel Erfahrung",
    onb_children_title: "Kinder im Haushalt?",
    onb_children_sub: "Wichtig für die Tiervermittlung.",
    onb_other_pets_title: "Andere Tiere zuhause?",
    onb_other_pets_sub: "Wir suchen verträgliche Kombinationen.",
    onb_yes: "Ja",
    onb_no: "Nein",
    onb_activity_title: "Wie aktiv bist du?",
    onb_activity_sub: "Dein Tier soll zu deinem Lifestyle passen.",
    onb_activity_athletic: "🏃 Sportlich",
    onb_activity_athletic_sub: "Viel Bewegung täglich",
    onb_activity_medium: "🚶 Mittel",
    onb_activity_medium_sub: "Regelmäßige Spaziergänge",
    onb_activity_calm: "🛋️ Ruhig",
    onb_activity_calm_sub: "Gemütliches Tempo",
    onb_work_title: "Deine Arbeitssituation?",
    onb_work_sub: "Tiere brauchen Zeit und Aufmerksamkeit.",
    onb_work_fulltime: "💼 Vollzeit",
    onb_work_parttime: "🕐 Teilzeit",
    onb_work_home: "🏠 Homeoffice",
    onb_work_none: "☀️ Nicht berufstätig",
    onb_back: "← Zurück",
    onb_next: "Weiter →",
    onb_finish: "Los geht's! 🎉",
    onb_err_not_logged_in: "Nicht angemeldet",

    // ── Onboarding Tierhalter ──
    onb_th_title: "Dein Haustier",
    onb_th_sub: "Erzähl uns von deinem Tier — wir finden passende Gassi- und Spieldate-Partner!",
    onb_th_photo: "Foto deines Tieres (optional)",
    onb_th_add_photo: "Foto hinzufügen",
    onb_th_type: "Mein Tier ist ein…",
    onb_th_dog: "🐶 Hund",
    onb_th_cat: "🐱 Katze",
    onb_th_name: "Name *",
    onb_th_name_placeholder: "z.B. Bella",
    onb_th_breed_age: "Rasse & Alter",
    onb_th_breed_placeholder: "Rasse (optional)",
    onb_th_age_placeholder: "Alter in Jahren",
    onb_th_size: "Größe",
    onb_th_size_small: "Klein",
    onb_th_size_medium: "Mittel",
    onb_th_size_large: "Groß",
    onb_th_size_giant: "Riese",
    onb_th_activity: "Wie aktiv ist dein Tier?",
    onb_th_activity_very: "🏃 Sehr aktiv",
    onb_th_activity_medium: "🚶 Mäßig aktiv",
    onb_th_activity_calm: "🛋 Ruhig",
    onb_th_behavior: "Verhalten",
    onb_th_child_friendly: "Kinderfreundlich",
    onb_th_animal_friendly: "Verträglich mit anderen Tieren",
    onb_th_desc: "Beschreibung (optional)",
    onb_th_desc_placeholder: "Erzähl etwas über dein Tier — Lieblingsrouten, Besonderheiten…",
    onb_th_btn: "🐾 Los geht's!",
    onb_th_err_name: "Bitte einen Namen für dein Tier eingeben.",

    // ── Onboarding Tierheim ──
    onb_shelter_title: "🏠 Tierheim einrichten",
    onb_shelter_sub: "Erzähl uns von deinem Tierheim",
    onb_shelter_name: "Name des Tierheims *",
    onb_shelter_name_placeholder: "z.B. Tierheim München",
    onb_shelter_address: "Adresse",
    onb_shelter_address_placeholder: "Straße, PLZ, Stadt",
    onb_shelter_phone: "Telefon",
    onb_shelter_phone_placeholder: "+49 ...",
    onb_shelter_desc: "Beschreibung",
    onb_shelter_desc_placeholder: "Erzähle etwas über euer Tierheim...",
    onb_shelter_btn: "Tierheim einrichten 🏠",
    onb_shelter_err_name: "Bitte den Namen des Tierheims eingeben.",

    // ── Tab Bar ──
    tab_discover: "Entdecken",
    tab_matches: "Matches",
    tab_chat: "Chat",
    tab_profile: "Profil",
    tab_messages: "Nachrichten",

    // ── Swipe / Filter ──
    filter_title: "Filter",
    filter_reset: "Zurücksetzen",
    filter_size: "Größe",
    filter_size_multiple: "Mehrere möglich",
    filter_size_small: "Klein",
    filter_size_medium: "Mittel",
    filter_size_large: "Groß",
    filter_size_giant: "Riese",
    filter_max_age: "Maximales Alter",
    filter_up_to: "Bis",
    filter_years: "Jahre",
    filter_years_abbr: "J.",
    filter_gender: "Geschlecht",
    filter_gender_all: "Alle",
    filter_gender_male: "♂ Männlich",
    filter_gender_female: "♀ Weiblich",
    filter_activity: "Aktivitätslevel",
    filter_activity_multiple: "Mehrere möglich",
    filter_activity_calm: "🛋 Ruhig",
    filter_activity_medium: "🚶 Mittel",
    filter_activity_athletic: "🏃 Sportlich",
    filter_children: "Kinderfreundlich",
    filter_doesnt_matter: "Egal",
    filter_yes: "✅ Ja",
    filter_garden: "Garten erforderlich",
    filter_garden_no: "✕ Nicht nötig",
    filter_garden_yes: "🌿 Braucht Garten",
    filter_other_animals: "Verträglich mit anderen Tieren",
    filter_radius: "Umkreis",
    filter_radius_all: "Alle",
    filter_radius_unlimited: "Unbegrenzt",
    filter_apply: "Filter anwenden",
    filter_dog_size: "Hundegröße",
    filter_dog_activity: "Aktivitätslevel des Hundes",
    filter_max_dog_age: "Max. Alter des Hundes",
    filter_owner_age: "Altersgruppe Besitzer",
    filter_owner_gender: "Geschlecht Besitzer",
    filter_deck_castrated_note: "Kastrierte Hunde werden automatisch ausgeblendet.",

    // ── Gassi Feed / Setup ──
    gassi_setup_title: "👤 Dein Profil",
    gassi_setup_subtitle: "Damit andere dich kennenlernen können",
    gassi_setup_photo_soon: "Profilfoto (kommt bald)",
    gassi_setup_label_firstname: "Vorname *",
    gassi_setup_label_age: "Alter *",
    gassi_setup_label_gender: "Geschlecht *",
    gassi_setup_label_city: "Stadt / Stadtteil *",
    gassi_setup_label_bio: "Kurze Bio (optional)",
    gassi_setup_ph_firstname: "z.B. Max",
    gassi_setup_ph_age: "z.B. 28",
    gassi_setup_ph_city: "z.B. München, Schwabing",
    gassi_setup_ph_bio: "Ich bin... (wird auf deiner Karte angezeigt)",
    gassi_setup_next: "Weiter →",
    gassi_setup_required_title: "Pflichtfeld",
    gassi_setup_required_name: "Bitte gib deinen Vornamen ein.",
    gassi_setup_required_age: "Bitte gib dein Alter ein.",
    gassi_setup_required_gender: "Bitte wähle dein Geschlecht.",
    gassi_setup_required_city: "Bitte gib deinen Stadtteil / deine Stadt ein.",
    gassi_register_title: "🐕 Hund registrieren",
    gassi_register_step2: "Schritt 2 von 2",
    gassi_register_label_name: "Name *",
    gassi_register_label_breed: "Rasse",
    gassi_register_label_age: "Alter (Jahre)",
    gassi_register_label_size: "Größe",
    gassi_register_label_activity: "Aktivitätslevel",
    gassi_register_label_mode: "Modus",
    gassi_register_ph_name: "z.B. Buddy",
    gassi_register_ph_breed: "z.B. Labrador",
    gassi_register_ph_age: "z.B. 3",
    gassi_register_missing_name_title: "Name fehlt",
    gassi_register_missing_name_msg: "Bitte gib deinem Hund einen Namen.",
    gassi_register_error_title: "Fehler",
    gassi_register_error_msg: "Konnte Hund nicht speichern.",
    gassi_dogs_modal_title: "🐕 Meine Hunde",
    gassi_dogs_modal_close: "Schließen",
    gassi_dogs_modal_mixed_breed: "Mischling",
    gassi_dogs_modal_change_mode: "⇄ Modus ändern",
    gassi_dogs_modal_add: "Neuen Hund anlegen",
    gassi_dogs_modal_change_mode_title: (dogName: string) => `Modus von ${dogName}`,
    gassi_feed_no_partners: "Keine Partner in der Nähe",
    gassi_feed_reload: "Nochmal laden",
    gassi_feed_back: "Modi",
    gassi_feed_match_owner: (name: string, city: string) => `Besitzer: ${name} · ${city}`,
    gassi_feed_match_desc: "Ihr habt euch gegenseitig geliked — schreibt euch!",
    gassi_feed_match_message: "💬 Nachricht schreiben",
    gassi_feed_match_keep_swiping: "Weiter swipen",
    swipe_demo_banner: "🐾 Demo-Modus — Anmelden um Anfragen zu speichern",
    swipe_match_desc: (shelterName: string) => `Du und ${shelterName} mögen einander — schreib jetzt eine Nachricht!`,

    // ── Swipe Mode Toggle ──
    swipe_mode_adoption: "Adoption",
    swipe_mode_gassi_zucht: "Gassidate & Zucht",
    swipe_sub_gassidate: "Gassidate",
    swipe_sub_zucht: "Zucht",
    swipe_badge_gassidate: "Gassidate",

    // ── Matches Screen ──
    matches_header: "❤️ Matches",
    matches_tab_adoption: "❤️ Adoption",
    matches_tab_gassi: "🐾 Gassi & Spieldate",
    matches_empty_adoption_title: "Noch keine Matches",
    matches_empty_adoption_sub: "Swipe rechts auf Tiere die dir gefallen — bei einem Match kannst du direkt mit dem Tierheim schreiben!",
    matches_empty_owner_title: "Noch keine Gassi-Matches",
    matches_empty_owner_sub: "Swipe auf andere Haustiere im Gassi & Spieldate-Modus — bei einem gegenseitigen Like könnt ihr euch verabreden!",
    matches_shelter_fallback: "Tierheim",
    matches_owner_fallback: "Tierhalter",
    matches_msg_placeholder_shelter: "Schreib dem Tierheim eine Nachricht…",
    matches_msg_placeholder_owner: "Schreib eine Nachricht…",
    matches_yesterday: "Gestern",
    matches_gassi_date: "Gassi-Date",
    matches_spieldate: "Spieldate",
    matches_unknown: "Unbekannt",

    // ── Profil Screen (tabs) ──
    profil_title: "Mein Profil",
    profil_tap_to_change: "Tippe auf das Bild um es zu ändern",
    profil_location: "Standort",
    profil_not_specified: "Nicht angegeben",
    profil_my_animals: "Meine Tiere",
    profil_add_dog: "Hund zur Adoption eintragen",
    profil_add_dog_sub: "Tier anlegen und Adoptierende finden",
    profil_all_animals: "Alle meine Tiere",
    profil_all_animals_sub: "Übersicht und Status verwalten",
    profil_sign_out: "Abmelden",
    profil_sign_out_confirm: "Möchtest du dich wirklich abmelden?",
    profil_cancel: "Abbrechen",
    profil_err_upload: "Upload fehlgeschlagen.",
    profil_no_name: "Kein Name",
    profil_role_adoptant: "Tiersucher",
    profil_role_tierhalter: "Tierhalter",
    profil_role_tierheim: "Tierheim",

    // ── Adoption Profil ──
    adoption_profil_living_apt: "🏢 Wohnung",
    adoption_profil_living_house: "🏠 Haus",
    adoption_profil_living_house_garden: "🌿 Haus mit Garten",
    adoption_profil_work_full: "💼 Vollzeit",
    adoption_profil_work_part: "⏰ Teilzeit",
    adoption_profil_work_home: "🏡 Homeoffice",
    adoption_profil_exp_beginner: "🌱 Anfänger",
    adoption_profil_exp_experienced: "⭐ Fortgeschritten",
    adoption_profil_exp_pro: "🏆 Profi",
    adoption_profil_edit_title: "Profil bearbeiten",
    adoption_profil_save: "Speichern",
    adoption_profil_label_name: "Vorname *",
    adoption_profil_label_age: "Alter",
    adoption_profil_label_gender: "Geschlecht",
    adoption_profil_label_city: "Stadt",
    adoption_profil_label_living: "Wohnsituation",
    adoption_profil_label_exp: "Erfahrung mit Hunden",
    adoption_profil_label_children: "Kinder im Haushalt",
    adoption_profil_label_animals: "Andere Tiere",
    adoption_profil_label_activity: "Aktivitätslevel",
    adoption_profil_label_work: "Arbeitszeit",
    adoption_profil_label_bio: "Kurze Bio",
    adoption_profil_placeholder_name: "Dein Vorname",
    adoption_profil_placeholder_age: "z.B. 28",
    adoption_profil_placeholder_city: "z.B. München",
    adoption_profil_placeholder_bio: "Erzähl etwas über dich…",
    adoption_profil_section: "Mein Profil",
    adoption_profil_complete: "Profil vervollständigen…",
    adoption_profil_role: "❤️ Tiersucher",
    adoption_profil_edit_btn: "✏️ Bearbeiten",
    adoption_profil_location: "Stadt",
    adoption_profil_location_label: "Wohnsituation",
    adoption_profil_exp_label: "Erfahrung mit Hunden",
    adoption_profil_activity_label: "Aktivitätslevel",
    adoption_profil_work_label: "Arbeitszeit",
    adoption_profil_children_label: "Kinder im Haushalt",
    adoption_profil_animals_label: "Andere Tiere",
    adoption_profil_yes: "Ja",
    adoption_profil_no: "Nein",
    adoption_profil_demo_location: "Standort",

    // ── Adoption Feed ──
    adoption_empty_title: "Keine Tiere mehr",
    adoption_empty_sub: "Du hast alle Tiere in deiner Nähe gesehen. Schau später nochmal vorbei!",
    adoption_reload: "Nochmal laden",
    adoption_activity_very: "🏃 Sehr aktiv",
    adoption_activity_medium: "🚶 Mäßig aktiv",
    adoption_activity_calm: "🛋 Ruhig",
    adoption_exp_beginner: "🌱 Einsteiger",
    adoption_exp_experienced: "⭐ Erfahren",
    adoption_exp_pro: "🏆 Nur Profis",
    adoption_children_yes: "Ja",
    adoption_children_no: "Nicht kinderfreundlich",
    adoption_children_school: "Ab Schulalter",
    adoption_children_teen: "Ab Teenager",
    adoption_feed_loading: "Tiere werden geladen…",
    adoption_feed_match_title: "Es ist ein Match!",
    adoption_feed_match_sub: (shelter: string) => `Du und ${shelter} mögen einander — schreib jetzt eine Nachricht!`,
    adoption_feed_msg_btn: "💬 Nachricht schreiben",
    adoption_feed_later: "Später",
    adoption_feed_char_label: "Charakter",
    adoption_feed_props_label: "Eigenschaften",
    adoption_feed_shelter_link: "Profil →",
    adoption_feed_garden_yes: "Ja",
    adoption_feed_garden_no: "Nein",
    adoption_feed_in_shelter_since: "Im Heim seit",

    // ── Adoption Matches ──
    adoption_matches_pending: "⏳ Ausstehend",
    adoption_matches_accepted: "✅ Angenommen",
    adoption_matches_rejected: "❌ Abgelehnt",
    adoption_matches_empty_title: "Noch keine Matches",
    adoption_matches_empty_sub: "Swipe rechts auf Tiere die dir gefallen — bei einem Match kannst du direkt mit dem Tierheim schreiben!",

    // ── Adoption Nachrichten ──
    adoption_nachrichten_demo_msg1: "Hallo! Wir freuen uns über dein Interesse an Bruno. Wann hättest du Zeit für ein erstes Kennenlernen?",
    adoption_nachrichten_demo_msg2: "Vielen Dank für deine Anfrage zu Milo! Wir melden uns in den nächsten 1–2 Werktagen.",

    // ── Pet Detail ──
    pet_match_title: "🎉 Es ist ein Match!",
    pet_match_msg: (name: string) => `Du hast ${name} geliked!\nDas Tierheim wird sich bald melden.`,
    pet_open_chat: "💬 Chat öffnen",
    pet_back: "Zurück",
    pet_exp_beginner: "🌱 Geeignet für Einsteiger",
    pet_exp_experienced: "⭐ Erfahrene Halter",
    pet_exp_pro: "🏆 Nur für Profis",
    pet_not_found: "Tier nicht gefunden.",
    pet_section_char: "Charakter",
    pet_section_props: "Eigenschaften",
    pet_section_shelter_since: "Im Tierheim seit",
    pet_label_garden: "Braucht Garten",
    pet_label_neutered: "Kastriert",
    pet_label_children: "Kinderfreundlich",
    pet_label_animals: "Verträglich mit anderen Tieren",
    pet_label_activity: "Aktivitätslevel",
    pet_label_exp: "Erfahrung",
    pet_yes: "Ja",
    pet_no: "Nein",
    pet_child_yes: "Ja, kinderfreundlich",
    pet_child_no: "Nicht kinderfreundlich",
    pet_child_school: "Ab Schulalter",
    pet_child_teen: "Ab Teenager",
    pet_activity_very: "🏃 Sehr aktiv",
    pet_activity_medium: "🚶 Mäßig aktiv",
    pet_activity_calm: "🛋 Ruhig",

    // ── Owner Chat ──
    owner_chat_placeholder: (name: string) => `Nachricht an ${name}…`,
    owner_chat_match_msg: (name: string, mode: string) => `${name} und du haben ein Match!\nVerabredet euch für einen ${mode}!`,

    // ── Shelter Add Pet ──
    shelter_add_title: "Hund hinzufügen",
    shelter_add_section_photos: "Fotos",
    shelter_add_section_basics: "Grunddaten",
    shelter_add_section_gender: "Geschlecht",
    shelter_add_section_size: "Größe",
    shelter_add_section_char: "Charakter-Tags",
    shelter_add_section_props: "Eigenschaften",
    shelter_add_section_children: "Kinderfreundlich",
    shelter_add_section_exp: "Benötigte Erfahrung",
    shelter_add_section_activity: "Aktivitätslevel",
    shelter_add_section_desc: "Beschreibung",
    shelter_add_label_name: "Name *",
    shelter_add_label_breed: "Rasse",
    shelter_add_label_age_years: "Alter (Jahre)",
    shelter_add_label_age_months: "Alter (Monate)",
    shelter_add_placeholder_name: "z.B. Max",
    shelter_add_placeholder_breed: "z.B. Labrador Retriever",
    shelter_add_placeholder_desc: "Erzähl etwas über den Hund…",
    shelter_add_photos_count: (sel: number, max: number) => `Bis zu ${max} Fotos · ${sel}/${max} ausgewählt`,
    shelter_add_uploading: "Fotos werden hochgeladen…",
    shelter_add_saving: "Wird gespeichert…",
    shelter_add_save_btn: "🐾 Hund speichern",
    shelter_add_saved_title: "Gespeichert! 🎉",
    shelter_add_saved_msg: (name: string) => `${name} wurde zur Adoption eingetragen.`,
    shelter_add_err_name: "Bitte einen Namen eingeben.",
    shelter_add_label_garden: "Braucht Garten",
    shelter_add_label_animals: "Verträglich mit anderen Tieren",

    // ── Gassi Feed ──
    gassi_mode_gassi: "Gassi-Date",
    gassi_mode_deck: "Deck-Date",
    gassi_bio_max: "Laufe gerne durch Parks und liebe lange Morgenspaziergänge. Mein Hund ist mein bester Freund!",
    gassi_bio_sophie: "Leidenschaftliche Hundemama seit 5 Jahren. Liebe Outdoor-Aktivitäten und freue mich über neue Hundekontakte.",
    gassi_bio_jonas: "Täglich 2 Stunden aktiv — mein Hund und ich sind unzertrennlich. Suche regelmäßige Gassipartner.",
    gassi_size_small: "Klein (< 10 kg)",
    gassi_size_medium: "Mittel (10–25 kg)",
    gassi_size_large: "Groß (25–40 kg)",
    gassi_size_giant: "Riese (> 40 kg)",
    gassi_activity_very: "🏃 Sehr aktiv",
    gassi_activity_medium: "🚶 Mäßig aktiv",
    gassi_activity_calm: "🛋 Ruhig",
    gassi_match_msg: "Match! Gassi-Date vereinbaren",
    gassi_near_you: "In deiner Nähe",
    gassi_year: "Jahr",
    gassi_years: "Jahre",

    // ── Gassi Profil ──
    gassi_profil_gender_male: "♂ Männlich",
    gassi_profil_gender_female: "♀ Weiblich",
    gassi_profil_gender_diverse: "⚧ Divers",
    gassi_profil_activity_calm: "🛋 Ruhig",
    gassi_profil_activity_medium: "🚶 Mittel",
    gassi_profil_activity_athletic: "🏃 Sportlich",
    gassi_profil_meeting_park: "🌳 Park",
    gassi_profil_meeting_forest: "🌲 Wald",
    gassi_profil_meeting_any: "🤷 Egal",
    gassi_profil_create_account: "Echtes Konto erstellen",
    gassi_profil_edit_title: "Profil bearbeiten",
    gassi_profil_save: "Speichern",
    gassi_profil_label_name: "Vorname *",
    gassi_profil_label_age: "Alter",
    gassi_profil_label_gender: "Geschlecht",
    gassi_profil_label_city: "Stadt / Stadtteil",
    gassi_profil_label_activity: "Aktivitätslevel",
    gassi_profil_label_meeting: "Bevorzugter Treffpunkt",
    gassi_profil_label_bio: "Kurze Bio",
    gassi_profil_placeholder_name: "Dein Vorname",
    gassi_profil_placeholder_age: "z.B. 28",
    gassi_profil_placeholder_city: "z.B. München, Schwabing",
    gassi_profil_placeholder_bio: "Erzähl etwas über dich und deinen Hund…",
    gassi_profil_section_my_profile: "Mein Profil",
    gassi_profil_complete: "Profil vervollständigen…",
    gassi_profil_role: "🐾 Tierhalter",
    gassi_profil_all_dogs: "Alle →",
    gassi_profil_add_first_dog: "Ersten Hund registrieren",
    gassi_profil_logout_title: "Abmelden",
    gassi_profil_save_failed: "Speichern fehlgeschlagen.",
    gassi_profil_upload_failed: "Upload fehlgeschlagen.",

    // ── Gassi Matches ──
    gassi_matches_gassi_date: "Gassi-Date",
    gassi_matches_spieldate: "Spieldate",
    gassi_matches_wait_match: "Warte auf Gegenmatch…",
    gassi_matches_status_pending: "⏳ Wartet",

    // ── Gassi Chat ──
    gassi_chat_gassi_date: "Gassi-Date",
    gassi_chat_spieldate: "Spieldate",
    gassi_chat_match_text: "haben ein Match!",
    gassi_chat_match_cta_gassi: "Verabredet euch für einen Gassi-Spaziergang!",
    gassi_chat_match_cta_play: "Verabredet euch für einen Spieldate!",
    gassi_chat_demo_msg1: "Hey Amir! Super dass wir gematcht haben 🐾",
    gassi_chat_demo_msg2: "Hey Max! Kira sieht toll aus. Wann wollt ihr gassi gehen?",
    gassi_chat_demo_msg3: "Morgen früh um 9 im Englischen Garten? 🌳",
    gassi_chat_demo_msg4: "Perfekt! Bis morgen 🐕",

    // ── Adoption Chat ──
    adoption_chat_shelter_fallback: "Tierheim",
    adoption_chat_today: "Heute",
    adoption_chat_yesterday: "Gestern",
    adoption_chat_match_cta: (petName: string) => `Ihr habt ein Match! Schreib dem Tierheim\neine erste Nachricht über ${petName}.`,
    adoption_chat_placeholder: (petName: string) => `Nachricht über ${petName}…`,
    adoption_chat_demo_msg1: "Hallo Amir! Vielen Dank für dein Interesse an Bruno 🐾",
    adoption_chat_demo_msg2: "Hallo! Bruno hat mich sofort begeistert. Wie läuft der Prozess ab?",
    adoption_chat_demo_msg3: "Super! Wir würden dich gerne zu einem Kennenlernen einladen.",
    adoption_chat_demo_msg4: "Das klingt wunderbar! Wann wäre das möglich?",
    adoption_chat_demo_msg5: "Wie wäre es am Samstag um 11 Uhr?",
    adoption_chat_demo_msg6: "Perfekt, ich freue mich! 🐕",

    // ── Gassi Meine Hunde ──
    gassi_my_dogs: "🐕 Meine Hunde",
    gassi_size_small_label: "Klein",
    gassi_size_medium_label: "Mittel",
    gassi_size_large_label: "Groß",
    gassi_size_giant_label: "Riese",
    gassi_dogs_count_singular: "Hund registriert",
    gassi_dogs_count_plural: "Hunde registriert",
    gassi_dogs_login_title: "Anmelden erforderlich",
    gassi_dogs_login_sub: "Melde dich an um deine Hunde zu verwalten und Gassidate-Partner zu finden.",
    gassi_dogs_login_btn: "Jetzt anmelden",
    gassi_dogs_empty_title: "Noch keine Hunde registriert",
    gassi_dogs_empty_sub: "Registriere deinen Hund um Gassidate-Partner in deiner Nähe zu finden!",
    gassi_dogs_register_btn: "Hund registrieren",
    gassi_dogs_mixed_breed: "Mischling",

    // ── Gassi Nachrichten ──
    gassi_nachr_title: "💬 Nachrichten",
    gassi_nachr_conversations_singular: "Gespräch",
    gassi_nachr_conversations_plural: "Gespräche",
    gassi_nachr_empty_title: "Noch keine Nachrichten",
    gassi_nachr_empty_sub: "Bei einem gegenseitigen Match könnt ihr euch direkt schreiben!",
    gassi_nachr_placeholder: "Schreib eine erste Nachricht!",
    gassi_nachr_demo_msg1: "Hey! Wollen wir morgen im Englischen Garten Gassi gehen? So gegen 10 Uhr?",
    gassi_nachr_demo_msg2: "Super dass wir gematcht haben! Cookie liebt andere Hunde, das wird toll 🐾",

    // ── Adoption Nachrichten ──
    adoption_nachr_title: "💬 Nachrichten",
    adoption_nachr_empty_title: "Noch keine Nachrichten",
    adoption_nachr_empty_sub: "Like ein Tier und schreib dem Tierheim eine Nachricht!",
    adoption_nachr_placeholder: "Schreib dem Tierheim eine Nachricht…",

    // ── Adoption Matches extra ──
    adoption_matches_wait_msg: "Anfrage gesendet, warte auf Bestätigung…",

    // ── Tierheim Layout ──
    tierheim_tab_dashboard: "Dashboard",
    tierheim_tab_dogs: "🐕 Hunde",
    tierheim_tab_requests: "🔔 Anfragen",
    tierheim_tab_profile: "👤 Profil",

    // ── Tierheim Dashboard ──
    tierheim_status_available: "Verfügbar",
    tierheim_status_reserved: "Reserviert",
    tierheim_status_placed: "Vermittelt",
    tierheim_age_puppy: "Welpe",
    tierheim_age_year: "Jahr",
    tierheim_age_years: "Jahre",
    tierheim_age_months: "Monate",
    tierheim_demo_name: "Demo-Tierheim",
    tierheim_demo_desc: "Wir vermitteln glückliche Hunde in liebevolle Zuhause.",

    // ── Tierheim Dashboard ──
    tierheim_dashboard_title: "🏠 Tierheim Dashboard",
    tierheim_dashboard_your_shelter: "Dein Tierheim",
    tierheim_dashboard_login: "Anmelden 🔑",
    tierheim_dashboard_quick_access: "Schnellzugriff",
    tierheim_dashboard_add_animal: "Tier hinzufügen",
    tierheim_dashboard_add_animal_sub: "Neues Tier zur Adoption eintragen",
    tierheim_dashboard_requests: "Anfragen",
    tierheim_dashboard_new_messages: (n: number) => `${n} neue Nachricht${n > 1 ? "en" : ""}`,
    tierheim_dashboard_interested: (n: number) => `${n} Interessenten`,
    tierheim_dashboard_all_dogs: (n: number) => `Alle Hunde (${n})`,
    tierheim_dashboard_stat_total: "Gesamt",
    tierheim_dashboard_stat_matches: "Matches",
    tierheim_dashboard_my_animals: "Meine Tiere",
    tierheim_dashboard_matches_nav: "Matches & Nachrichten",
    tierheim_dashboard_manage_animals: (n: number) => `${n} Tiere verwalten`,
    tierheim_dashboard_demo_title: "Demo-Ansicht",
    tierheim_dashboard_demo_sub: "Melde dich an, um dein echtes Tierheim zu verwalten",
    tierheim_matches_title: "Matches & Nachrichten",
    tierheim_matches_empty_title: "Noch keine Matches",
    tierheim_matches_empty_sub: "Sobald jemand ein Tier von euch liked, erscheint hier ein Match.",
    tierheim_dogs_my_animals: "Meine Tiere",
    tierheim_dogs_add_short: "+ Tier",
    tierheim_dogs_empty_sub2: "Füge dein erstes Tier hinzu!",
    tierheim_chat_placeholder: (name: string) => `Nachricht an ${name}…`,
    tierheim_chat_greeting: (adoptantName: string, petName: string) => `${adoptantName} interessiert sich für ${petName}.\nSchreib eine Begrüßung!`,
    gassi_individual_filter_active: "⚙️ Individueller Filter aktiv",
    gassi_mixed_breed: "Mischling",
    gassi_dog_owner_fallback: "Hundehalter",

    // ── Tierheim Hunde ──
    tierheim_dogs_demo_title: "Demo-Ansicht",
    tierheim_dogs_demo_msg: "Melde dich an um den Status zu ändern.",
    tierheim_dogs_demo_add_msg: "Melde dich an um Hunde hinzuzufügen.",
    tierheim_dogs_demo_delete_msg: "Melde dich an um Tiere zu löschen.",
    tierheim_dogs_empty_title: "Noch keine Tiere",
    tierheim_dogs_empty_sub: "Trage deinen ersten Hund ein und finde ein neues Zuhause!",
    tierheim_dogs_add_btn: "Tier hinzufügen",
    tierheim_dogs_status_change: "⇄ Status ändern",
    tierheim_dogs_status_title: "Status von",
    tierheim_dogs_status_current: "Aktuell:",
    tierheim_dogs_delete_title: "löschen?",
    tierheim_dogs_delete_msg: "Alle Fotos und Matches werden ebenfalls gelöscht.",
    tierheim_dogs_delete_btn: "Löschen",
    tierheim_dogs_cancel: "Abbrechen",
    tierheim_dogs_verfuegbar: "Verfügbar",
    tierheim_dogs_reserviert: "Reserviert",
    tierheim_dogs_vermittelt: "Vermittelt",
    tierheim_dogs_puppy: "Welpe",
    tierheim_dogs_year: "Jahr",
    tierheim_dogs_years: "Jahre",
    tierheim_dogs_months: "Monate",

    // ── Tierheim Detail (adoption/tierheim/[id]) ──
    adoption_tierheim_contact: "Kontakt",
    adoption_tierheim_available_header: "Verfügbare Hunde",
    adoption_tierheim_no_pets: "Aktuell sind keine Tiere verfügbar.",

    // ── Tierheim Profil ──
    tierheim_profil_edit_cancel: "Abbrechen",
    tierheim_profil_edit_title: "Profil bearbeiten",
    tierheim_profil_save: "Speichern",
    tierheim_profil_label_name: "Name des Tierheims",
    tierheim_profil_label_city: "Stadt",
    tierheim_profil_label_address: "Adresse",
    tierheim_profil_label_phone: "Telefon",
    tierheim_profil_label_email: "E-Mail",
    tierheim_profil_label_website: "Website",
    tierheim_profil_label_hours: "Öffnungszeiten",
    tierheim_profil_label_founded: "Gegründet seit (Jahr)",
    tierheim_profil_label_cert: "Zertifizierungen / Verband (optional)",
    tierheim_profil_label_desc: "Beschreibung",
    tierheim_profil_placeholder_name: "z.B. Tierheim München",
    tierheim_profil_placeholder_city: "z.B. München",
    tierheim_profil_placeholder_address: "Musterstraße 1, 80331 München",
    tierheim_profil_placeholder_phone: "+49 89 123456",
    tierheim_profil_placeholder_email: "info@mein-tierheim.de",
    tierheim_profil_placeholder_website: "www.mein-tierheim.de",
    tierheim_profil_placeholder_hours: "Mo–Fr 9–18 Uhr, Sa 10–15 Uhr",
    tierheim_profil_placeholder_founded: "z.B. 2005",
    tierheim_profil_placeholder_cert: "z.B. Tierschutzbund Bayern",
    tierheim_profil_placeholder_desc: "Erzählt uns etwas über euer Tierheim…",
    tierheim_profil_dogs_available: "Hunde verfügbar",
    tierheim_profil_founded: "Gegründet",
    tierheim_profil_contact_section: "Kontakt & Infos",
    tierheim_profil_phone_label: "Telefon",
    tierheim_profil_email_label: "E-Mail",
    tierheim_profil_website_label: "Website",
    tierheim_profil_address_label: "Adresse",
    tierheim_profil_hours_label: "Öffnungszeiten",
    tierheim_profil_add_contact: "Kontaktdaten hinzufügen…",
    tierheim_profil_role: "🏠 Tierheim",
    tierheim_profil_fallback_name: "Mein Tierheim",
    tierheim_profil_login_btn: "Jetzt anmelden 🔑",
    tierheim_profil_edit_profile_btn: "✏️ Bearbeiten",

    // ── Tierheim Anfragen ──
    tierheim_req_pending: "Ausstehend",
    tierheim_req_accepted: "Angenommen",
    tierheim_req_rejected: "Abgelehnt",
    tierheim_req_empty_title: "Noch keine Anfragen",
    tierheim_req_empty_sub: "Sobald jemand eines eurer Tiere liked, erscheint hier eine Anfrage.",
    tierheim_req_demo_view: "Demo-Ansicht",
    tierheim_req_demo_login_msg: "Melde dich an um Anfragen zu bearbeiten.",
    tierheim_req_subtitle_singular: "Interessent",
    tierheim_req_subtitle_plural: "Interessenten",
    tierheim_req_from: "von",
    tierheim_req_unknown: "Unbekannt",
    tierheim_req_new_match: "Neuer Match — schreib eine Begrüßung!",
    tierheim_req_you: "Du: ",
    tierheim_req_reject_title: "Anfrage ablehnen",
    tierheim_req_reject_btn: "✕ Ablehnen",
    tierheim_req_accept_btn: "✓ Annehmen",
    tierheim_req_cancel: "Abbrechen",
    tierheim_req_yesterday: "Gestern",
    tierheim_req_guest_nav: "Interessent",
    tierheim_req_demo_name1: "Anna M.",
    tierheim_req_demo_name2: "Tom K.",
    tierheim_req_demo_name3: "Julia S.",
    tierheim_req_demo_city1: "München",
    tierheim_req_demo_city2: "Hamburg",
    tierheim_req_demo_city3: "Berlin",
    tierheim_req_demo_msg1: "Hallo! Wir würden Buddy gerne kennenlernen.",
    tierheim_req_demo_msg2: "Wann können wir vorbeikommen?",

    // ── Shelter Add Pet ──
    shelter_size_small: "Klein (< 10 kg)",
    shelter_size_medium: "Mittel (10–25 kg)",
    shelter_size_large: "Groß (25–45 kg)",
    shelter_size_giant: "Riese (> 45 kg)",
    shelter_gender_male: "Männlich",
    shelter_gender_female: "Weiblich",
    shelter_exp_beginner: "🌱 Anfänger",
    shelter_exp_intermediate: "⭐ Fortgeschrittene",
    shelter_exp_pro: "🏆 Nur Profis",
    shelter_activity_very: "🏃 Sehr aktiv",
    shelter_activity_medium: "🚶 Mäßig aktiv",
    shelter_activity_calm: "🛋 Ruhig",
    shelter_children_yes: "Ja",
    shelter_children_no: "Nein",
    shelter_children_school: "Ab Schulalter",
    shelter_children_teen: "Ab Teenager",
    shelter_traits_playful: "verspielt",
    shelter_traits_cuddly: "verschmust",
    shelter_traits_calm: "ruhig",
    shelter_traits_loyal: "treu",
    shelter_traits_curious: "neugierig",
    shelter_traits_energetic: "energetisch",
    shelter_traits_family: "familienfreundlich",
    shelter_traits_eager: "lernfreudig",
    shelter_max_photos: "Maximum erreicht",
    shelter_max_photos_msg: (n: number) => `Du kannst maximal ${n} Fotos hinzufügen.`,
    shelter_err_name: "Bitte einen Namen eingeben.",
    shelter_neutered: "Kastriert",
    shelter_section_photo: "Foto",
    shelter_section_breed_age: "Rasse & Alter",
    shelter_section_size: "Größe",
    shelter_section_behavior: "Verhalten",
    shelter_section_traits: "Charakter-Tags",
    shelter_section_desc: "Beschreibung",

    // ── Components ──
    comp_back: "Zurück",
    comp_switch_modes: "Modi wechseln",
    comp_warning_title: "Passt das wirklich?",
    comp_warning_like_anyway: "Trotzdem liken ❤️",
    comp_warning_cancel: "Abbrechen",
    comp_pet_more: "mehr...",
    comp_pet_view_all: "Alle Details ansehen →",
    comp_pet_garden: "Garten",
    comp_pet_children: "Kinder",
    comp_pet_animals: "Tiere",
    comp_pet_exp_beginner: "Einsteiger",
    comp_pet_exp_experienced: "Erfahren",
    comp_pet_exp_pro: "Profi",
    comp_owner_very_active: "🏃 Sehr aktiv",
    comp_owner_medium: "🚶 Mäßig aktiv",
    comp_owner_calm: "🛋 Ruhig",
    comp_owner_small: "Klein",
    comp_owner_medium_size: "Mittel",
    comp_owner_large: "Groß",
    comp_owner_giant: "Riese",
    comp_owner_puppy: "Welpe",
    comp_owner_year: "Jahr",
    comp_owner_years: "Jahre",
    comp_owner_child_friendly: "👦 Kinderfreundlich",
    comp_owner_animal_friendly: "🐾 Tierfreundlich",
    comp_owner_near_you: "In deiner Nähe",
    comp_badge_playful: "verspielt",
    comp_badge_cuddly: "verschmust",
    comp_badge_calm: "ruhig",
    comp_badge_energetic: "energiegeladen",
    comp_badge_loyal: "treu",
    comp_badge_curious: "neugierig",
    comp_badge_gentle: "sanft",
    comp_badge_brave: "mutig",
    comp_badge_child_loving: "kinderlieb",
    comp_badge_affectionate: "anhänglich",

    gassi_chat_placeholder: (name: string) => `Nachricht an ${name}…`,
    tip_title: "💡 Tipp",
    shelter_tip_body: "Füge möglichst viele Fotos und eine detaillierte Beschreibung hinzu — Tiere mit vollständigen Profilen werden häufiger geliked!",
    tierheim_tip_body: "Füge möglichst viele Fotos und eine detaillierte Beschreibung hinzu — Profile mit Fotos werden 3x häufiger geliked!",

    // ── General ──
    err_generic: "Fehler",
    err_not_logged_in: "Nicht angemeldet",
  },

  en: {
    // ── Splash / Index ──
    splash_dog_seeker_title: "Dog Seekers",
    splash_dog_seeker_sub: "Find your perfect dog",
    splash_dog_owner_title: "Dog Owners",
    splash_dog_owner_sub: "Walk dates & breeding for dog owners",
    splash_shelter_title: "Animal Shelter",
    splash_shelter_sub: "Manage animals & process requests",
    splash_login_link: "Already registered? Sign in →",

    // ── Auth ──
    login_welcome_back: "Welcome back!",
    login_title: "Sign In",
    login_email: "Email",
    login_email_placeholder: "your@email.com",
    login_password: "Password",
    login_btn: "Sign In",
    login_or: "or",
    login_google: "Sign in with Google",
    login_apple: "Sign in with Apple",
    login_no_account: "No account yet?",
    login_register: "Register",
    login_err_missing: "Missing Information",
    login_err_missing_msg: "Please enter your email and password.",
    login_err_failed: "Login failed",

    // ── Register ──
    register_back: "← Back",
    register_step_role_title: "Who are you?",
    register_step_role_sub: "Choose your role to get started",
    register_step_details_title: "Your Account",
    register_step_details_sub: "Create your free account",
    register_role_adoptant_label: "I'm looking for a pet",
    register_role_adoptant_desc: "Adopt a pet from a shelter",
    register_role_tierhalter_label: "I have a pet",
    register_role_tierhalter_desc: "Find dog walk & playdate partners",
    register_role_tierheim_label: "I am a shelter",
    register_role_tierheim_desc: "Place animals with loving families",
    register_next: "Continue →",
    register_name: "Name",
    register_name_placeholder: "Your name",
    register_email_placeholder: "your@email.com",
    register_password_placeholder: "At least 6 characters",
    register_change: "change",
    register_create_btn: "Create account 🎉",
    register_has_account: "Already have an account?",
    register_sign_in: "Sign In",
    register_err_missing: "Missing Information",
    register_err_missing_msg: "Please fill in all fields.",
    register_err_pw_short: "Password too short",
    register_err_pw_short_msg: "At least 6 characters required.",
    register_err_no_user: "No user created.",
    register_err_failed: "Registration failed",
    register_pick_role: "Choose a role",
    register_pick_role_msg: "Please choose a role to continue.",

    // ── Onboarding Adoptant ──
    onb_step: "Step",
    onb_of: "of",
    onb_housing_title: "How do you live?",
    onb_housing_sub: "This helps us find matching animals.",
    onb_housing_apartment: "🏢 Apartment",
    onb_housing_house: "🏡 House",
    onb_housing_garden: "🌿 House with garden",
    onb_housing_farm: "🚜 Farm",
    onb_exp_title: "Your experience with animals?",
    onb_exp_sub: "Be honest — for your sake and the animal's.",
    onb_exp_beginner: "🌱 Beginner",
    onb_exp_beginner_sub: "First pet",
    onb_exp_intermediate: "⭐ Intermediate",
    onb_exp_intermediate_sub: "Some experience",
    onb_exp_pro: "🏆 Expert",
    onb_exp_pro_sub: "Lots of experience",
    onb_children_title: "Children in household?",
    onb_children_sub: "Important for animal placement.",
    onb_other_pets_title: "Other pets at home?",
    onb_other_pets_sub: "We look for compatible combinations.",
    onb_yes: "Yes",
    onb_no: "No",
    onb_activity_title: "How active are you?",
    onb_activity_sub: "Your pet should fit your lifestyle.",
    onb_activity_athletic: "🏃 Athletic",
    onb_activity_athletic_sub: "Lots of daily exercise",
    onb_activity_medium: "🚶 Moderate",
    onb_activity_medium_sub: "Regular walks",
    onb_activity_calm: "🛋️ Calm",
    onb_activity_calm_sub: "Leisurely pace",
    onb_work_title: "Your work situation?",
    onb_work_sub: "Animals need time and attention.",
    onb_work_fulltime: "💼 Full-time",
    onb_work_parttime: "🕐 Part-time",
    onb_work_home: "🏠 Work from home",
    onb_work_none: "☀️ Not employed",
    onb_back: "← Back",
    onb_next: "Continue →",
    onb_finish: "Let's go! 🎉",
    onb_err_not_logged_in: "Not logged in",

    // ── Onboarding Tierhalter ──
    onb_th_title: "Your Pet",
    onb_th_sub: "Tell us about your pet — we'll find matching walk and playdate partners!",
    onb_th_photo: "Photo of your pet (optional)",
    onb_th_add_photo: "Add photo",
    onb_th_type: "My pet is a…",
    onb_th_dog: "🐶 Dog",
    onb_th_cat: "🐱 Cat",
    onb_th_name: "Name *",
    onb_th_name_placeholder: "e.g. Bella",
    onb_th_breed_age: "Breed & Age",
    onb_th_breed_placeholder: "Breed (optional)",
    onb_th_age_placeholder: "Age in years",
    onb_th_size: "Size",
    onb_th_size_small: "Small",
    onb_th_size_medium: "Medium",
    onb_th_size_large: "Large",
    onb_th_size_giant: "Giant",
    onb_th_activity: "How active is your pet?",
    onb_th_activity_very: "🏃 Very active",
    onb_th_activity_medium: "🚶 Moderately active",
    onb_th_activity_calm: "🛋 Calm",
    onb_th_behavior: "Behavior",
    onb_th_child_friendly: "Child-friendly",
    onb_th_animal_friendly: "Compatible with other animals",
    onb_th_desc: "Description (optional)",
    onb_th_desc_placeholder: "Tell us about your pet — favorite routes, special traits…",
    onb_th_btn: "🐾 Let's go!",
    onb_th_err_name: "Please enter a name for your pet.",

    // ── Onboarding Tierheim ──
    onb_shelter_title: "🏠 Set up shelter",
    onb_shelter_sub: "Tell us about your shelter",
    onb_shelter_name: "Shelter name *",
    onb_shelter_name_placeholder: "e.g. Munich Animal Shelter",
    onb_shelter_address: "Address",
    onb_shelter_address_placeholder: "Street, zip code, city",
    onb_shelter_phone: "Phone",
    onb_shelter_phone_placeholder: "+1 ...",
    onb_shelter_desc: "Description",
    onb_shelter_desc_placeholder: "Tell us something about your shelter...",
    onb_shelter_btn: "Set up shelter 🏠",
    onb_shelter_err_name: "Please enter the shelter name.",

    // ── Tab Bar ──
    tab_discover: "Discover",
    tab_matches: "Matches",
    tab_chat: "Chat",
    tab_profile: "Profile",
    tab_messages: "Messages",

    // ── Swipe / Filter ──
    filter_title: "Filter",
    filter_reset: "Reset",
    filter_size: "Size",
    filter_size_multiple: "Multiple possible",
    filter_size_small: "Small",
    filter_size_medium: "Medium",
    filter_size_large: "Large",
    filter_size_giant: "Giant",
    filter_max_age: "Maximum age",
    filter_up_to: "Up to",
    filter_years: "years",
    filter_years_abbr: "yr.",
    filter_gender: "Gender",
    filter_gender_all: "All",
    filter_gender_male: "♂ Male",
    filter_gender_female: "♀ Female",
    filter_activity: "Activity level",
    filter_activity_multiple: "Multiple possible",
    filter_activity_calm: "🛋 Calm",
    filter_activity_medium: "🚶 Moderate",
    filter_activity_athletic: "🏃 Athletic",
    filter_children: "Child-friendly",
    filter_doesnt_matter: "Doesn't matter",
    filter_yes: "✅ Yes",
    filter_garden: "Garden required",
    filter_garden_no: "✕ Not needed",
    filter_garden_yes: "🌿 Needs garden",
    filter_other_animals: "Compatible with other animals",
    filter_radius: "Radius",
    filter_radius_all: "All",
    filter_radius_unlimited: "Unlimited",
    filter_apply: "Apply filters",
    filter_dog_size: "Dog size",
    filter_dog_activity: "Dog's activity level",
    filter_max_dog_age: "Max. dog age",
    filter_owner_age: "Owner age group",
    filter_owner_gender: "Owner gender",
    filter_deck_castrated_note: "Neutered dogs are automatically hidden.",

    // ── Gassi Feed / Setup ──
    gassi_setup_title: "👤 Your Profile",
    gassi_setup_subtitle: "So others can get to know you",
    gassi_setup_photo_soon: "Profile photo (coming soon)",
    gassi_setup_label_firstname: "First name *",
    gassi_setup_label_age: "Age *",
    gassi_setup_label_gender: "Gender *",
    gassi_setup_label_city: "City / District *",
    gassi_setup_label_bio: "Short bio (optional)",
    gassi_setup_ph_firstname: "e.g. Max",
    gassi_setup_ph_age: "e.g. 28",
    gassi_setup_ph_city: "e.g. Munich, Altona",
    gassi_setup_ph_bio: "I am... (shown on your card)",
    gassi_setup_next: "Next →",
    gassi_setup_required_title: "Required",
    gassi_setup_required_name: "Please enter your first name.",
    gassi_setup_required_age: "Please enter your age.",
    gassi_setup_required_gender: "Please select your gender.",
    gassi_setup_required_city: "Please enter your neighborhood / city.",
    gassi_register_title: "🐕 Register Dog",
    gassi_register_step2: "Step 2 of 2",
    gassi_register_label_name: "Name *",
    gassi_register_label_breed: "Breed",
    gassi_register_label_age: "Age (years)",
    gassi_register_label_size: "Size",
    gassi_register_label_activity: "Activity level",
    gassi_register_label_mode: "Mode",
    gassi_register_ph_name: "e.g. Buddy",
    gassi_register_ph_breed: "e.g. Labrador",
    gassi_register_ph_age: "e.g. 3",
    gassi_register_missing_name_title: "Name missing",
    gassi_register_missing_name_msg: "Please give your dog a name.",
    gassi_register_error_title: "Error",
    gassi_register_error_msg: "Could not save dog.",
    gassi_dogs_modal_title: "🐕 My Dogs",
    gassi_dogs_modal_close: "Close",
    gassi_dogs_modal_mixed_breed: "Mixed breed",
    gassi_dogs_modal_change_mode: "⇄ Change mode",
    gassi_dogs_modal_add: "Add new dog",
    gassi_dogs_modal_change_mode_title: (dogName: string) => `Mode of ${dogName}`,
    gassi_feed_no_partners: "No partners nearby",
    gassi_feed_reload: "Load again",
    gassi_feed_back: "Modes",
    gassi_feed_match_owner: (name: string, city: string) => `Owner: ${name} · ${city}`,
    gassi_feed_match_desc: "You both liked each other — send a message!",
    gassi_feed_match_message: "💬 Send a message",
    gassi_feed_match_keep_swiping: "Keep swiping",
    swipe_demo_banner: "🐾 Demo mode — Sign in to save requests",
    swipe_match_desc: (shelterName: string) => `You and ${shelterName} like each other — send a message now!`,

    // ── Swipe Mode Toggle ──
    swipe_mode_adoption: "Adoption",
    swipe_mode_gassi_zucht: "Walk & Breeding",
    swipe_sub_gassidate: "Walk Date",
    swipe_sub_zucht: "Breeding",
    swipe_badge_gassidate: "Walk Date",

    // ── Matches Screen ──
    matches_header: "❤️ Matches",
    matches_tab_adoption: "❤️ Adoption",
    matches_tab_gassi: "🐾 Walk & Playdate",
    matches_empty_adoption_title: "No matches yet",
    matches_empty_adoption_sub: "Swipe right on animals you like — when you match, you can message the shelter directly!",
    matches_empty_owner_title: "No walk matches yet",
    matches_empty_owner_sub: "Swipe on other pets in walk & playdate mode — when you both like each other, you can arrange to meet!",
    matches_shelter_fallback: "Animal Shelter",
    matches_owner_fallback: "Pet Owner",
    matches_msg_placeholder_shelter: "Message the shelter…",
    matches_msg_placeholder_owner: "Write a message…",
    matches_yesterday: "Yesterday",
    matches_gassi_date: "Walk Date",
    matches_spieldate: "Playdate",
    matches_unknown: "Unknown",

    // ── Profil Screen (tabs) ──
    profil_title: "My Profile",
    profil_tap_to_change: "Tap the image to change it",
    profil_location: "Location",
    profil_not_specified: "Not specified",
    profil_my_animals: "My Animals",
    profil_add_dog: "List dog for adoption",
    profil_add_dog_sub: "Create an animal and find adopters",
    profil_all_animals: "All my animals",
    profil_all_animals_sub: "Manage overview and status",
    profil_sign_out: "Sign Out",
    profil_sign_out_confirm: "Do you really want to sign out?",
    profil_cancel: "Cancel",
    profil_err_upload: "Upload failed.",
    profil_no_name: "No name",
    profil_role_adoptant: "Pet Seeker",
    profil_role_tierhalter: "Pet Owner",
    profil_role_tierheim: "Animal Shelter",

    // ── Adoption Profil ──
    adoption_profil_living_apt: "🏢 Apartment",
    adoption_profil_living_house: "🏠 House",
    adoption_profil_living_house_garden: "🌿 House with garden",
    adoption_profil_work_full: "💼 Full-time",
    adoption_profil_work_part: "⏰ Part-time",
    adoption_profil_work_home: "🏡 Work from home",
    adoption_profil_exp_beginner: "🌱 Beginner",
    adoption_profil_exp_experienced: "⭐ Intermediate",
    adoption_profil_exp_pro: "🏆 Expert",
    adoption_profil_edit_title: "Edit Profile",
    adoption_profil_save: "Save",
    adoption_profil_label_name: "First Name *",
    adoption_profil_label_age: "Age",
    adoption_profil_label_gender: "Gender",
    adoption_profil_label_city: "City",
    adoption_profil_label_living: "Living situation",
    adoption_profil_label_exp: "Experience with dogs",
    adoption_profil_label_children: "Children in household",
    adoption_profil_label_animals: "Other pets",
    adoption_profil_label_activity: "Activity level",
    adoption_profil_label_work: "Work schedule",
    adoption_profil_label_bio: "Short bio",
    adoption_profil_placeholder_name: "Your first name",
    adoption_profil_placeholder_age: "e.g. 28",
    adoption_profil_placeholder_city: "e.g. Munich",
    adoption_profil_placeholder_bio: "Tell us something about yourself…",
    adoption_profil_section: "My Profile",
    adoption_profil_complete: "Complete profile…",
    adoption_profil_role: "❤️ Pet Seeker",
    adoption_profil_edit_btn: "✏️ Edit",
    adoption_profil_location: "City",
    adoption_profil_location_label: "Living situation",
    adoption_profil_exp_label: "Experience with dogs",
    adoption_profil_activity_label: "Activity level",
    adoption_profil_work_label: "Work schedule",
    adoption_profil_children_label: "Children in household",
    adoption_profil_animals_label: "Other pets",
    adoption_profil_yes: "Yes",
    adoption_profil_no: "No",
    adoption_profil_demo_location: "Location",

    // ── Adoption Feed ──
    adoption_empty_title: "No more animals",
    adoption_empty_sub: "You've seen all animals near you. Check back later!",
    adoption_reload: "Reload",
    adoption_activity_very: "🏃 Very active",
    adoption_activity_medium: "🚶 Moderately active",
    adoption_activity_calm: "🛋 Calm",
    adoption_exp_beginner: "🌱 Beginner",
    adoption_exp_experienced: "⭐ Experienced",
    adoption_exp_pro: "🏆 Experts only",
    adoption_children_yes: "Yes",
    adoption_children_no: "Not child-friendly",
    adoption_children_school: "School age+",
    adoption_children_teen: "Teens+",
    adoption_feed_loading: "Loading animals…",
    adoption_feed_match_title: "It's a match!",
    adoption_feed_match_sub: (shelter: string) => `You and ${shelter} like each other — send a message now!`,
    adoption_feed_msg_btn: "💬 Send message",
    adoption_feed_later: "Later",
    adoption_feed_char_label: "Character",
    adoption_feed_props_label: "Properties",
    adoption_feed_shelter_link: "Profile →",
    adoption_feed_garden_yes: "Yes",
    adoption_feed_garden_no: "No",
    adoption_feed_in_shelter_since: "In shelter since",

    // ── Adoption Matches ──
    adoption_matches_pending: "⏳ Pending",
    adoption_matches_accepted: "✅ Accepted",
    adoption_matches_rejected: "❌ Rejected",
    adoption_matches_empty_title: "No matches yet",
    adoption_matches_empty_sub: "Swipe right on animals you like — when you match, you can message the shelter directly!",

    // ── Adoption Nachrichten ──
    adoption_nachrichten_demo_msg1: "Hello! We're happy about your interest in Bruno. When would you have time for an initial meeting?",
    adoption_nachrichten_demo_msg2: "Thank you for your inquiry about Milo! We'll get back to you within 1–2 business days.",

    // ── Pet Detail ──
    pet_match_title: "🎉 It's a match!",
    pet_match_msg: (name: string) => `You liked ${name}!\nThe shelter will be in touch soon.`,
    pet_open_chat: "💬 Open chat",
    pet_back: "Back",
    pet_exp_beginner: "🌱 Suitable for beginners",
    pet_exp_experienced: "⭐ Experienced owners",
    pet_exp_pro: "🏆 Experts only",
    pet_not_found: "Animal not found.",
    pet_section_char: "Character",
    pet_section_props: "Properties",
    pet_section_shelter_since: "In shelter since",
    pet_label_garden: "Needs garden",
    pet_label_neutered: "Neutered",
    pet_label_children: "Child-friendly",
    pet_label_animals: "Compatible with other animals",
    pet_label_activity: "Activity level",
    pet_label_exp: "Experience",
    pet_yes: "Yes",
    pet_no: "No",
    pet_child_yes: "Yes, child-friendly",
    pet_child_no: "Not child-friendly",
    pet_child_school: "School age+",
    pet_child_teen: "Teens+",
    pet_activity_very: "🏃 Very active",
    pet_activity_medium: "🚶 Moderately active",
    pet_activity_calm: "🛋 Calm",

    // ── Owner Chat ──
    owner_chat_placeholder: (name: string) => `Message to ${name}…`,
    owner_chat_match_msg: (name: string, mode: string) => `${name} and you have a match!\nArrange a ${mode}!`,

    // ── Shelter Add Pet ──
    shelter_add_title: "Add Dog",
    shelter_add_section_photos: "Photos",
    shelter_add_section_basics: "Basic Info",
    shelter_add_section_gender: "Gender",
    shelter_add_section_size: "Size",
    shelter_add_section_char: "Character Tags",
    shelter_add_section_props: "Properties",
    shelter_add_section_children: "Child-friendly",
    shelter_add_section_exp: "Required Experience",
    shelter_add_section_activity: "Activity Level",
    shelter_add_section_desc: "Description",
    shelter_add_label_name: "Name *",
    shelter_add_label_breed: "Breed",
    shelter_add_label_age_years: "Age (Years)",
    shelter_add_label_age_months: "Age (Months)",
    shelter_add_placeholder_name: "e.g. Max",
    shelter_add_placeholder_breed: "e.g. Labrador Retriever",
    shelter_add_placeholder_desc: "Tell us something about the dog…",
    shelter_add_photos_count: (sel: number, max: number) => `Up to ${max} photos · ${sel}/${max} selected`,
    shelter_add_uploading: "Uploading photos…",
    shelter_add_saving: "Saving…",
    shelter_add_save_btn: "🐾 Save dog",
    shelter_add_saved_title: "Saved! 🎉",
    shelter_add_saved_msg: (name: string) => `${name} has been listed for adoption.`,
    shelter_add_err_name: "Please enter a name.",
    shelter_add_label_garden: "Needs garden",
    shelter_add_label_animals: "Compatible with other animals",

    // ── Gassi Feed ──
    gassi_mode_gassi: "Walk Date",
    gassi_mode_deck: "Breeding Date",
    gassi_bio_max: "I love running through parks and enjoy long morning walks. My dog is my best friend!",
    gassi_bio_sophie: "Passionate dog mom for 5 years. Love outdoor activities and enjoy meeting new dog owners.",
    gassi_bio_jonas: "Active 2 hours daily — my dog and I are inseparable. Looking for regular walking partners.",
    gassi_size_small: "Small (< 10 kg)",
    gassi_size_medium: "Medium (10–25 kg)",
    gassi_size_large: "Large (25–40 kg)",
    gassi_size_giant: "Giant (> 40 kg)",
    gassi_activity_very: "🏃 Very active",
    gassi_activity_medium: "🚶 Moderately active",
    gassi_activity_calm: "🛋 Calm",
    gassi_match_msg: "Match! Arrange a walk date",
    gassi_near_you: "Near you",
    gassi_year: "year",
    gassi_years: "years",

    // ── Gassi Profil ──
    gassi_profil_gender_male: "♂ Male",
    gassi_profil_gender_female: "♀ Female",
    gassi_profil_gender_diverse: "⚧ Non-binary",
    gassi_profil_activity_calm: "🛋 Calm",
    gassi_profil_activity_medium: "🚶 Moderate",
    gassi_profil_activity_athletic: "🏃 Athletic",
    gassi_profil_meeting_park: "🌳 Park",
    gassi_profil_meeting_forest: "🌲 Forest",
    gassi_profil_meeting_any: "🤷 Anywhere",
    gassi_profil_create_account: "Create an Account",
    gassi_profil_edit_title: "Edit Profile",
    gassi_profil_save: "Save",
    gassi_profil_label_name: "First Name *",
    gassi_profil_label_age: "Age",
    gassi_profil_label_gender: "Gender",
    gassi_profil_label_city: "City / District",
    gassi_profil_label_activity: "Activity Level",
    gassi_profil_label_meeting: "Preferred Meeting Spot",
    gassi_profil_label_bio: "Short Bio",
    gassi_profil_placeholder_name: "Your first name",
    gassi_profil_placeholder_age: "e.g. 28",
    gassi_profil_placeholder_city: "e.g. Munich, Schwabing",
    gassi_profil_placeholder_bio: "Tell us something about you and your dog…",
    gassi_profil_section_my_profile: "My Profile",
    gassi_profil_complete: "Complete profile…",
    gassi_profil_role: "🐾 Pet Owner",
    gassi_profil_all_dogs: "All →",
    gassi_profil_add_first_dog: "Register first dog",
    gassi_profil_logout_title: "Sign Out",
    gassi_profil_save_failed: "Failed to save.",
    gassi_profil_upload_failed: "Upload failed.",

    // ── Gassi Matches ──
    gassi_matches_gassi_date: "Walk Date",
    gassi_matches_spieldate: "Playdate",
    gassi_matches_wait_match: "Waiting for mutual match…",
    gassi_matches_status_pending: "⏳ Waiting",

    // ── Gassi Chat ──
    gassi_chat_gassi_date: "Walk Date",
    gassi_chat_spieldate: "Playdate",
    gassi_chat_match_text: "it's a match!",
    gassi_chat_match_cta_gassi: "Schedule a walk together!",
    gassi_chat_match_cta_play: "Schedule a playdate together!",
    gassi_chat_demo_msg1: "Hey Amir! So glad we matched 🐾",
    gassi_chat_demo_msg2: "Hey Max! Kira looks great. When do you want to go for a walk?",
    gassi_chat_demo_msg3: "Tomorrow morning at 9 in the English Garden? 🌳",
    gassi_chat_demo_msg4: "Perfect! See you tomorrow 🐕",

    // ── Adoption Chat ──
    adoption_chat_shelter_fallback: "Shelter",
    adoption_chat_today: "Today",
    adoption_chat_yesterday: "Yesterday",
    adoption_chat_match_cta: (petName: string) => `You matched! Send the shelter\nyour first message about ${petName}.`,
    adoption_chat_placeholder: (petName: string) => `Message about ${petName}…`,
    adoption_chat_demo_msg1: "Hi Amir! Thank you so much for your interest in Bruno 🐾",
    adoption_chat_demo_msg2: "Hi! Bruno caught my eye immediately. How does the process work?",
    adoption_chat_demo_msg3: "Great! We'd love to invite you for a meet and greet.",
    adoption_chat_demo_msg4: "That sounds wonderful! When would that be possible?",
    adoption_chat_demo_msg5: "How about Saturday at 11am?",
    adoption_chat_demo_msg6: "Perfect, I'm looking forward to it! 🐕",

    // ── Gassi Meine Hunde ──
    gassi_my_dogs: "🐕 My Dogs",
    gassi_size_small_label: "Small",
    gassi_size_medium_label: "Medium",
    gassi_size_large_label: "Large",
    gassi_size_giant_label: "Giant",
    gassi_dogs_count_singular: "dog registered",
    gassi_dogs_count_plural: "dogs registered",
    gassi_dogs_login_title: "Login Required",
    gassi_dogs_login_sub: "Sign in to manage your dogs and find walk partners.",
    gassi_dogs_login_btn: "Sign in now",
    gassi_dogs_empty_title: "No dogs registered yet",
    gassi_dogs_empty_sub: "Register your dog to find walk partners near you!",
    gassi_dogs_register_btn: "Register dog",
    gassi_dogs_mixed_breed: "Mixed breed",

    // ── Gassi Nachrichten ──
    gassi_nachr_title: "💬 Messages",
    gassi_nachr_conversations_singular: "conversation",
    gassi_nachr_conversations_plural: "conversations",
    gassi_nachr_empty_title: "No messages yet",
    gassi_nachr_empty_sub: "When you have a mutual match, you can message each other directly!",
    gassi_nachr_placeholder: "Send the first message!",
    gassi_nachr_demo_msg1: "Hey! Want to go for a walk in the park tomorrow around 10am?",
    gassi_nachr_demo_msg2: "So glad we matched! Cookie loves other dogs, this will be great 🐾",

    // ── Adoption Nachrichten ──
    adoption_nachr_title: "💬 Messages",
    adoption_nachr_empty_title: "No messages yet",
    adoption_nachr_empty_sub: "Like an animal and message the shelter!",
    adoption_nachr_placeholder: "Message the shelter…",

    // ── Adoption Matches extra ──
    adoption_matches_wait_msg: "Request sent, waiting for confirmation…",

    // ── Tierheim Layout ──
    tierheim_tab_dashboard: "Dashboard",
    tierheim_tab_dogs: "🐕 Dogs",
    tierheim_tab_requests: "🔔 Requests",
    tierheim_tab_profile: "👤 Profile",

    // ── Tierheim Dashboard ──
    tierheim_status_available: "Available",
    tierheim_status_reserved: "Reserved",
    tierheim_status_placed: "Placed",
    tierheim_age_puppy: "Puppy",
    tierheim_age_year: "year",
    tierheim_age_years: "years",
    tierheim_age_months: "months",
    tierheim_demo_name: "Demo Shelter",
    tierheim_demo_desc: "We place happy dogs with loving families.",

    // ── Tierheim Dashboard ──
    tierheim_dashboard_title: "🏠 Shelter Dashboard",
    tierheim_dashboard_your_shelter: "Your Shelter",
    tierheim_dashboard_login: "Sign in 🔑",
    tierheim_dashboard_quick_access: "Quick Access",
    tierheim_dashboard_add_animal: "Add animal",
    tierheim_dashboard_add_animal_sub: "Register a new animal for adoption",
    tierheim_dashboard_requests: "Requests",
    tierheim_dashboard_new_messages: (n: number) => `${n} new message${n > 1 ? "s" : ""}`,
    tierheim_dashboard_interested: (n: number) => `${n} interested person${n > 1 ? "s" : ""}`,
    tierheim_dashboard_all_dogs: (n: number) => `All Animals (${n})`,
    tierheim_dashboard_stat_total: "Total",
    tierheim_dashboard_stat_matches: "Matches",
    tierheim_dashboard_my_animals: "My Animals",
    tierheim_dashboard_matches_nav: "Matches & Messages",
    tierheim_dashboard_manage_animals: (n: number) => `Manage ${n} animals`,
    tierheim_dashboard_demo_title: "Demo View",
    tierheim_dashboard_demo_sub: "Sign in to manage your real shelter",
    tierheim_matches_title: "Matches & Messages",
    tierheim_matches_empty_title: "No matches yet",
    tierheim_matches_empty_sub: "Once someone likes one of your animals, a match will appear here.",
    tierheim_dogs_my_animals: "My Animals",
    tierheim_dogs_add_short: "+ Animal",
    tierheim_dogs_empty_sub2: "Add your first animal!",
    tierheim_chat_placeholder: (name: string) => `Message to ${name}…`,
    tierheim_chat_greeting: (adoptantName: string, petName: string) => `${adoptantName} is interested in ${petName}.\nSend a greeting!`,
    gassi_individual_filter_active: "⚙️ Individual filter active",
    gassi_mixed_breed: "Mixed breed",
    gassi_dog_owner_fallback: "Dog Owner",

    // ── Tierheim Hunde ──
    tierheim_dogs_demo_title: "Demo View",
    tierheim_dogs_demo_msg: "Sign in to change status.",
    tierheim_dogs_demo_add_msg: "Sign in to add dogs.",
    tierheim_dogs_demo_delete_msg: "Sign in to delete animals.",
    tierheim_dogs_empty_title: "No animals yet",
    tierheim_dogs_empty_sub: "Add your first dog and find a new home!",
    tierheim_dogs_add_btn: "Add animal",
    tierheim_dogs_status_change: "⇄ Change status",
    tierheim_dogs_status_title: "Status of",
    tierheim_dogs_status_current: "Current:",
    tierheim_dogs_delete_title: "delete?",
    tierheim_dogs_delete_msg: "All photos and matches will also be deleted.",
    tierheim_dogs_delete_btn: "Delete",
    tierheim_dogs_cancel: "Cancel",
    tierheim_dogs_verfuegbar: "Available",
    tierheim_dogs_reserviert: "Reserved",
    tierheim_dogs_vermittelt: "Placed",
    tierheim_dogs_puppy: "Puppy",
    tierheim_dogs_year: "year",
    tierheim_dogs_years: "years",
    tierheim_dogs_months: "months",

    // ── Tierheim Detail (adoption/tierheim/[id]) ──
    adoption_tierheim_contact: "Contact",
    adoption_tierheim_available_header: "Available Animals",
    adoption_tierheim_no_pets: "Currently no animals available.",

    // ── Tierheim Profil ──
    tierheim_profil_edit_cancel: "Cancel",
    tierheim_profil_edit_title: "Edit Profile",
    tierheim_profil_save: "Save",
    tierheim_profil_label_name: "Shelter name",
    tierheim_profil_label_city: "City",
    tierheim_profil_label_address: "Address",
    tierheim_profil_label_phone: "Phone",
    tierheim_profil_label_email: "Email",
    tierheim_profil_label_website: "Website",
    tierheim_profil_label_hours: "Opening hours",
    tierheim_profil_label_founded: "Founded (year)",
    tierheim_profil_label_cert: "Certifications / Association (optional)",
    tierheim_profil_label_desc: "Description",
    tierheim_profil_placeholder_name: "e.g. Munich Animal Shelter",
    tierheim_profil_placeholder_city: "e.g. Munich",
    tierheim_profil_placeholder_address: "Main St 1, 80331 Munich",
    tierheim_profil_placeholder_phone: "+1 555 123456",
    tierheim_profil_placeholder_email: "info@my-shelter.com",
    tierheim_profil_placeholder_website: "www.my-shelter.com",
    tierheim_profil_placeholder_hours: "Mon–Fri 9am–6pm, Sat 10am–3pm",
    tierheim_profil_placeholder_founded: "e.g. 2005",
    tierheim_profil_placeholder_cert: "e.g. Animal Welfare Association",
    tierheim_profil_placeholder_desc: "Tell us something about your shelter…",
    tierheim_profil_dogs_available: "Dogs available",
    tierheim_profil_founded: "Founded",
    tierheim_profil_contact_section: "Contact & Info",
    tierheim_profil_phone_label: "Phone",
    tierheim_profil_email_label: "Email",
    tierheim_profil_website_label: "Website",
    tierheim_profil_address_label: "Address",
    tierheim_profil_hours_label: "Opening hours",
    tierheim_profil_add_contact: "Add contact details…",
    tierheim_profil_role: "🏠 Animal Shelter",
    tierheim_profil_fallback_name: "My Shelter",
    tierheim_profil_login_btn: "Sign in now 🔑",
    tierheim_profil_edit_profile_btn: "✏️ Edit",

    // ── Tierheim Anfragen ──
    tierheim_req_pending: "Pending",
    tierheim_req_accepted: "Accepted",
    tierheim_req_rejected: "Rejected",
    tierheim_req_empty_title: "No requests yet",
    tierheim_req_empty_sub: "Once someone likes one of your animals, a request will appear here.",
    tierheim_req_demo_view: "Demo View",
    tierheim_req_demo_login_msg: "Sign in to process requests.",
    tierheim_req_subtitle_singular: "interested person",
    tierheim_req_subtitle_plural: "interested people",
    tierheim_req_from: "from",
    tierheim_req_unknown: "Unknown",
    tierheim_req_new_match: "New match — send a greeting!",
    tierheim_req_you: "You: ",
    tierheim_req_reject_title: "Reject request",
    tierheim_req_reject_btn: "✕ Reject",
    tierheim_req_accept_btn: "✓ Accept",
    tierheim_req_cancel: "Cancel",
    tierheim_req_yesterday: "Yesterday",
    tierheim_req_guest_nav: "Interested person",
    tierheim_req_demo_name1: "Anna M.",
    tierheim_req_demo_name2: "Tom K.",
    tierheim_req_demo_name3: "Julia S.",
    tierheim_req_demo_city1: "Munich",
    tierheim_req_demo_city2: "Hamburg",
    tierheim_req_demo_city3: "Berlin",
    tierheim_req_demo_msg1: "Hello! We'd love to meet Buddy.",
    tierheim_req_demo_msg2: "When can we come by?",

    // ── Shelter Add Pet ──
    shelter_size_small: "Small (< 10 kg)",
    shelter_size_medium: "Medium (10–25 kg)",
    shelter_size_large: "Large (25–45 kg)",
    shelter_size_giant: "Giant (> 45 kg)",
    shelter_gender_male: "Male",
    shelter_gender_female: "Female",
    shelter_exp_beginner: "🌱 Beginner",
    shelter_exp_intermediate: "⭐ Intermediate",
    shelter_exp_pro: "🏆 Experts only",
    shelter_activity_very: "🏃 Very active",
    shelter_activity_medium: "🚶 Moderately active",
    shelter_activity_calm: "🛋 Calm",
    shelter_children_yes: "Yes",
    shelter_children_no: "No",
    shelter_children_school: "School age+",
    shelter_children_teen: "Teens+",
    shelter_traits_playful: "playful",
    shelter_traits_cuddly: "cuddly",
    shelter_traits_calm: "calm",
    shelter_traits_loyal: "loyal",
    shelter_traits_curious: "curious",
    shelter_traits_energetic: "energetic",
    shelter_traits_family: "family-friendly",
    shelter_traits_eager: "eager to learn",
    shelter_max_photos: "Maximum reached",
    shelter_max_photos_msg: (n: number) => `You can add a maximum of ${n} photos.`,
    shelter_err_name: "Please enter a name.",
    shelter_neutered: "Neutered",
    shelter_section_photo: "Photo",
    shelter_section_breed_age: "Breed & Age",
    shelter_section_size: "Size",
    shelter_section_behavior: "Behavior",
    shelter_section_traits: "Character Tags",
    shelter_section_desc: "Description",

    // ── Components ──
    comp_back: "Back",
    comp_switch_modes: "Switch modes",
    comp_warning_title: "Are you sure?",
    comp_warning_like_anyway: "Like anyway ❤️",
    comp_warning_cancel: "Cancel",
    comp_pet_more: "more...",
    comp_pet_view_all: "View all details →",
    comp_pet_garden: "Garden",
    comp_pet_children: "Children",
    comp_pet_animals: "Animals",
    comp_pet_exp_beginner: "Beginner",
    comp_pet_exp_experienced: "Experienced",
    comp_pet_exp_pro: "Expert",
    comp_owner_very_active: "🏃 Very active",
    comp_owner_medium: "🚶 Moderately active",
    comp_owner_calm: "🛋 Calm",
    comp_owner_small: "Small",
    comp_owner_medium_size: "Medium",
    comp_owner_large: "Large",
    comp_owner_giant: "Giant",
    comp_owner_puppy: "Puppy",
    comp_owner_year: "year",
    comp_owner_years: "years",
    comp_owner_child_friendly: "👦 Child-friendly",
    comp_owner_animal_friendly: "🐾 Pet-friendly",
    comp_owner_near_you: "Near you",
    comp_badge_playful: "playful",
    comp_badge_cuddly: "cuddly",
    comp_badge_calm: "calm",
    comp_badge_energetic: "energetic",
    comp_badge_loyal: "loyal",
    comp_badge_curious: "curious",
    comp_badge_gentle: "gentle",
    comp_badge_brave: "brave",
    comp_badge_child_loving: "child-loving",
    comp_badge_affectionate: "affectionate",

    gassi_chat_placeholder: (name: string) => `Message to ${name}…`,
    tip_title: "💡 Tip",
    shelter_tip_body: "Add as many photos and a detailed description as possible — animals with complete profiles are liked more often!",
    tierheim_tip_body: "Add as many photos and a detailed description as possible — profiles with photos are liked 3× more often!",

    // ── General ──
    err_generic: "Error",
    err_not_logged_in: "Not logged in",
  },
} as const;

export type TranslationKey = keyof typeof translations.de;
export type Translations = typeof translations.de;

// ─── Context ─────────────────────────────────────────────────────────────────

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "de",
  setLang: () => {},
  t: translations.de,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("de");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((stored) => {
      if (stored === "de" || stored === "en") setLangState(stored);
    });
  }, []);

  const setLang = async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem(STORAGE_KEY, l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
